### ISSUE TITLE
最新版渲染与NPCmod渲染冲突导致客户端崩溃

### ISSUE THREAD

**Issue by SIZStan** [TartaricAcid/TouhouLittleMaid#173]
Description: Rendering entity in world

java.lang.NoSuchMethodError: net.minecraft.client.renderer.entity.NPCRendererHelper.renderModel(Lnet/minecraft/entity/EntityLivingBase;FFFFFFLnet/minecraft/client/renderer/entity/RenderLivingBase;Lnet/minecraft/client/model/ModelBase;Lnet/minecraft/util/ResourceLocation;)V
	at com.github.tartaricacid.touhoulittlemaid.client.renderer.entity.EntityCustomNpcChangeRender.renderModel(EntityCustomNpcChangeRender.java:164)
	at com.github.tartaricacid.touhoulittlemaid.client.renderer.entity.EntityCustomNpcChangeRender.func_77036_a(EntityCustomNpcChangeRender.java:43)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:240)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(RenderLiving.java:50)
	at noppes.npcs.client.renderer.RenderNPCInterface.doRender(RenderNPCInterface.java:166)
	at com.github.tartaricacid.touhoulittlemaid.client.renderer.entity.EntityCustomNpcChangeRender.doRender(EntityCustomNpcChangeRender.java:101)
	at com.github.tartaricacid.touhoulittlemaid.client.renderer.entity.EntityCustomNpcChangeRender.func_76986_a(EntityCustomNpcChangeRender.java:43)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:839)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1800)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by TartaricAcid** [comment]
没有完整的错误报告么？

**Comment by SIZStan** [comment]
NPC版本过久，已解决，嘻嘻
