### ISSUE TITLE
跟RC铁路12.0.0相冲突

### ISSUE THREAD

**Issue by fengeraien** [TartaricAcid/TouhouLittleMaid#176]
女仆mod版本：1.1.8-beta-hotfix2
RC版本：12.0.0

是在Catserver服务器发生的错误，确定是这俩mod的问题，两个删除任一就可以顺利启动服务端。

Catserver报错文件：

`
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Railcraft (railcraft)
Caused by: net.minecraft.util.ReportedException: Loading Railcraft Module
	at mods.railcraft.common.modules.RailcraftModuleManager.processStage(RailcraftModuleManager.java:266)
	at mods.railcraft.common.modules.RailcraftModuleManager.init(RailcraftModuleManager.java:236)
	at mods.railcraft.common.core.Railcraft.init(Railcraft.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:636)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:339)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:275)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/github/tartaricacid/touhoulittlemaid/proxy/ClientProxy
	at com.github.tartaricacid.touhoulittlemaid.item.ItemSpellCard.setCustomSpellCardEntry(ItemSpellCard.java:42)
	at com.github.tartaricacid.touhoulittlemaid.item.ItemSpellCard.func_150895_a(ItemSpellCard.java:76)
	at mods.railcraft.common.fluids.FluidContainerHandler.init(FluidContainerHandler.java:40)
	at mods.railcraft.common.fluids.FluidContainerHandler.findCanDrain(FluidContainerHandler.java:51)
	at mods.railcraft.common.util.crafting.FluidIngredient.<init>(FluidIngredient.java:41)
	at mods.railcraft.common.util.crafting.Ingredients.from(Ingredients.java:40)
	at mods.railcraft.common.plugins.forge.CraftingPlugin.cleanRecipeArray(CraftingPlugin.java:91)
	at mods.railcraft.common.plugins.forge.CraftingPlugin.processRecipe(CraftingPlugin.java:116)
	at mods.railcraft.common.plugins.forge.CraftingPlugin.makeShapedRecipe(CraftingPlugin.java:180)
	at mods.railcraft.common.plugins.forge.CraftingPlugin.addShapedRecipe(CraftingPlugin.java:137)
	at mods.railcraft.common.plugins.forge.CraftingPlugin.addShapedRecipe(CraftingPlugin.java:122)
	at mods.railcraft.common.items.ItemTie.defineRecipes(ItemTie.java:42)
	at java.util.Optional.ifPresent(Unknown Source)
	at mods.railcraft.common.core.IRailcraftObjectContainer.defineRecipes(IRailcraftObjectContainer.java:71)
	at mods.railcraft.common.modules.RailcraftModulePayload$BaseModuleEventHandler.lambda$init$1(RailcraftModulePayload.java:87)
	at java.lang.Iterable.forEach(Unknown Source)
	at mods.railcraft.common.modules.RailcraftModulePayload$BaseModuleEventHandler.init(RailcraftModulePayload.java:84)
	at mods.railcraft.common.modules.RailcraftModuleManager$Stage$3.passToModule(RailcraftModuleManager.java:318)
	at mods.railcraft.common.modules.RailcraftModuleManager.processStage(RailcraftModuleManager.java:253)
	... 37 more
Caused by: java.lang.ClassNotFoundException: com.github.tartaricacid.touhoulittlemaid.proxy.ClientProxy
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 56 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@433e536f from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 58 more
Caused by: java.lang.RuntimeException: Attempted to load class com/github/tartaricacid/touhoulittlemaid/proxy/ClientProxy for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 60 more
`

**Comment by TartaricAcid** [comment]
已经在 https://github.com/TartaricAcid/TouhouLittleMaid/pull/166 中修复
