### ISSUE TITLE
女仆手提音响播放的音乐无法听到

### ISSUE THREAD

**Issue by RisingInIris2017** [TartaricAcid/TouhouLittleMaid#272]
#### MOD版本 - Mod version:

1.12.2-1.2.2-release

#### Forge版本 - Forge version:

14.23.5.2854

#### 单人/多人游戏？ - Singleplayer or Multiplayer:

单人游戏和多人游戏均发生此现象。

#### 完整的MOD列表 - Installed mods:

https://paste.ubuntu.com/p/Z4tFH7kDwh/

#### 产生Bug的步骤 - How to reproduce:

1. 将手提音响放置在地上，任意指定一首音乐。
2. 将打开音乐的音响推给女仆，女仆提起音响。
3. 可以看到女仆开始摇头，但是游戏音效没有任何变化，没有听到音乐。
4. 将音效设置中所有的选项都拉到最大，也没有听到音乐。
5. 任意从网易云音乐平台找了一个歌单导入手提音响，播放里面的音乐，仍听不到音乐声音。

**Comment by rcdraft** [comment]
截获一段可疑的异常
<code>
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: java.net.MalformedURLException
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at java.net.URL.<init>(URL.java:627)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at java.net.URL.<init>(URL.java:490)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at java.net.URL.<init>(URL.java:439)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler.onMessage(PortableAudioMessageToClient.java:58)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler.onMessage(PortableAudioMessageToClient.java:46)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:56)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:36)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:274)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:99)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleClientSideCustomPacket(NetworkDispatcher.java:382)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:268)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:72)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:443)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.local.LocalChannel.access$500(LocalChannel.java:49)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:397)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [com.github.tartaricacid.touhoulittlemaid.network.simpleimpl.PortableAudioMessageToClient$Handler:onMessage:74]: 	at java.lang.Thread.run(Thread.java:748)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at java.net.URL.<init>(URL.java:532)
[15:50:55] [Netty Local Client IO #0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 44 more
</code>

**Comment by TartaricAcid** [comment]
你用的是 HMCL 启动器么？更新到最新版试试

**Comment by RisingInIris2017** [comment]
> 你用的是 HMCL 启动器么？更新到最新版试试
是。
我查出问题的HMCL启动器版本为3.3.172。

**Comment by RainSeaiZinc** [comment]
### 版本信息 - Versions

**MOD版本 - Mod version:**
1.12.2-1.2.2-release

**Forge版本 - Forge version:**
14.23.5.2854

**所使用的mod列表：**
https://pastebin.ubuntu.com/p/9Xcx46p9CC/

单人/多人游戏？ - Singleplayer or Multiplayer:
单人游戏和多人游戏均发生此现象。

### 问题描述 - Description of the problem
在多人游戏中一部分人能够听到音乐，但另外一部分人不行。且听不到音乐的玩家在播放音乐时不会显示字幕。
且尝试过更换启动器均无法解决问题。使用过的启动器包括HMCL Nsiso Launcher。

**Comment by RainSeaiZinc** [comment]
### 版本信息 - Versions

**MOD版本 - Mod version:**
1.12.2-1.2.2-release

**Forge版本 - Forge version:**
14.23.5.2854

**所使用的mod列表：**
https://pastebin.ubuntu.com/p/9Xcx46p9CC/

单人/多人游戏？ - Singleplayer or Multiplayer:
单人游戏和多人游戏均发生此现象。

### 问题描述 - Description of the problem
在多人游戏中一部分人能够听到音乐，但另外一部分人不行。且听不到音乐的玩家在播放音乐时不会显示字幕。
且尝试过更换启动器均无法解决问题。使用过的启动器包括HMCL Nsiso Launcher。

**Comment by TartaricAcid** [comment]
@RisingInIris2017 你说的这个问题我这边完全无法复现（甚至对方把有问题的整合包打包发给我，结果我这边也一切正常，所以我需要你直接通过 qq 群之类的东西联系我，我给你发带有调试信息的模组，你把启动后的日志发给我）

**Comment by RainSeaiZinc** [comment]
> @RisingInIris2017 你说的这个问题我这边完全无法复现（甚至对方把有问题的整合包打包发给我，结果我这边也一切正常，所以我需要你直接通过 qq 群之类的东西联系我，我给你发带有调试信息的模组，你把启动后的日志发给我）

这边的整合包在几天后又能够重新播放歌曲了，个人怀疑是mod跟网易云服务器之间通信的关系

**Comment by RisingInIris2017** [comment]
> @RisingInIris2017 你说的这个问题我这边完全无法复现（甚至对方把有问题的整合包打包发给我，结果我这边也一切正常，所以我需要你直接通过 qq 群之类的东西联系我，我给你发带有调试信息的模组，你把启动后的日志发给我）

收到，已经通过 [Discord](https://discord.com/channels/316493876103872512/658633415381352448/744922679559323728) 发送消息给你了。

**Comment by TartaricAcid** [comment]
新版本已经解决此问题
