### ISSUE TITLE
Crashing on multiplayer server start up.

### ISSUE THREAD

**Issue by qqbone** [TartaricAcid/TouhouLittleMaid#337]
### Minecraft Version

- [ ] 1.12.2
- [X] 1.16.5

### What happened?

Works fine in single player, is this mod not capable of server compatibility? It crashes via start up. Also I apologize I've never used Github before so not sure what this auto formatting is.

[13.10 20:41:46] [Server] -- Head --
[13.10 20:41:46] [Server] Threadmain
[13.10 20:41:46] [Server] Stacktrace:
[13.10 20:41:46] [Server] 	at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] -- MOD touhou_little_maid --
[13.10 20:41:46] [Server] Details:
[13.10 20:41:46] [Server] 	Caused by java.lang.NoClassDefFoundError: net/minecraft/client/renderer/tileentity/ItemStackTileEntityRenderer
[13.10 20:41:46] [Server] 		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.lang.Class.getDeclaredMethod(Class.java:2128) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at net.minecraftforge.eventbus.EventBus.getDeclMethod(EventBus.java:83) ~[eventbus-4.0.0.jar:?] {}
[13.10 20:41:46] [Server] 		at net.minecraftforge.eventbus.EventBus.lambda$null$4(EventBus.java:95) ~[eventbus-4.0.0.jar:?] {}
[13.10 20:41:46] [Server] 		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1577) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at net.minecraftforge.eventbus.EventBus.lambda$registerObject$7(EventBus.java:97) ~[eventbus-4.0.0.jar:?] {}
[13.10 20:41:46] [Server] 		at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:94) ~[eventbus-4.0.0.jar:?] {}
[13.10 20:41:46] [Server] 		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:120) ~[eventbus-4.0.0.jar:?] {}
[13.10 20:41:46] [Server] 		at com.github.tartaricacid.touhoulittlemaid.item.ItemSubstituteJizo.<init>(ItemSubstituteJizo.java:26) ~[touhou_little_maid:?] {re:classloading,pl:runtimedistcleaner:A}
[13.10 20:41:46] [Server] 		at net.minecraftforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:124) ~[forge:?] {re:classloading}
[13.10 20:41:46] [Server] 		at net.minecraftforge.registries.DeferredRegister.addEntries(DeferredRegister.java:200) ~[forge:?] {re:classloading}
[13.10 20:41:46] [Server] 		at net.minecraftforge.registries.DeferredRegister.access$000(DeferredRegister.java:61) ~[forge:?] {re:classloading}
[13.10 20:41:46] [Server] 		at net.minecraftforge.registries.DeferredRegister$EventDispatcher.handleEvent(DeferredRegister.java:172) ~[forge:?] {re:classloading}
[13.10 20:41:46] [Server] 		at net.minecraftforge.eventbus.ASMEventHandler_1_EventDispatcher_handleEvent_Register.invoke(.dynamic) ~[?:?] {}
[13.10 20:41:46] [Server] 		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
[13.10 20:41:46] [Server] 		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
[13.10 20:41:46] [Server] 		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
[13.10 20:41:46] [Server] 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.{re:classloading}
[13.10 20:41:46] [Server] 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
[13.10 20:41:46] [Server] 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[forge:?] {re:classloading}
[13.10 20:41:46] [Server] 		at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[forge:?] {re:classloading}
[13.10 20:41:46] [Server] 		at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:249) ~[forge:?] {re:classloading}
[13.10 20:41:46] [Server] 		at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:236) ~[forge:?] {re:classloading}
[13.10 20:41:46] [Server] 		at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:202) ~[forge:?] {re:classloading}
[13.10 20:41:46] [Server] 		at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
[13.10 20:41:46] [Server] 		at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
[13.10 20:41:46] [Server] 		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_{}
[13.10 20:41:46] [Server] 		at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.0.jar:36.{}
[13.10 20:41:46] [Server] 		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
[13.10 20:41:46] [Server] 		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
[13.10 20:41:46] [Server] 		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
[13.10 20:41:46] [Server] 		at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
[13.10 20:41:46] [Server] 		at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
[13.10 20:41:46] [Server] 		at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.0.jar:?] {}
[13.10 20:41:46] [Server] 		at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.0.jar:?] {}
[13.10 20:41:46] [Server] 		at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.0.jar:?] {}
[13.10 20:41:46] [Server] 	Mod Filetouhoulittlemaid-1.16.5-1.0.0.jar

**Comment by FaiDreaM** [comment]
Did you add Mod:Patchouli?

**Comment by qqbone** [comment]
Someone asked if I had the libraries, I'm using Patchouli 1.6.4 53.2
Wouldn't be able to run it on solo client without out. I always test before uploading to a server.
 20 gig server around 200 mods, same mods on client but works regularly, only few server sided mods. I can post the log when I'm home.
Removed the mod and server will start up fine.
I will also test it starting up on a new map, I'm unsure if it can be injected into a previous map.

**Comment by hexoctal-sur** [comment]
Also run into same issue.
The crash log is here [https://paste.ubuntu.com/p/P4Kd3qQjnW/](https://paste.ubuntu.com/p/P4Kd3qQjnW/)

**Comment by TartaricAcid** [comment]
fix in https://github.com/TartaricAcid/TouhouLittleMaid/commit/b615495f233d27262896480b1fab8480ab5bec27

**Comment by TartaricAcid** [comment]
@1420125167 fix in https://github.com/TartaricAcid/TouhouLittleMaid/commit/152c01e24d69d95ed2418fc27599452fdd5b2973
