### ISSUE TITLE
[Bug] [1.12.2] Crashed when used with RTM 2.4.23-42

### ISSUE THREAD

**Issue by AliceIndex** [TartaricAcid/TouhouLittleMaid#402]
### Minecraft Version

- [X] 1.12.2
- [ ] 1.16.5

### What happened?

Crashed when used with RTM .
Without RTM, successfully started.

### Relevant log output

```shell
---- Minecraft Crash Report ----

WARNING: coremods are present:
  PatchingFixRtmCorePlugin (fixRtm-2.0.23.jar)
  FixRtmCorePlugin (fixRtm-2.0.23.jar)
  JarInJarLoaderCoreMod (fixRtm-2.0.23.jar)
  HookingFixRtmCorePlugin (fixRtm-2.0.23.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 11/5/22 8:25 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Touhou Little Maid (touhou_little_maid)
Caused by: java.lang.IllegalAccessError: tried to access class jdk.nashorn.api.scripting.ScriptObjectMirror$11 from class jdk.nashorn.api.scripting.ScriptObjectMirror
	at jdk.nashorn.api.scripting.ScriptObjectMirror.containsKey(ScriptObjectMirror.java:345)
	at javax.script.SimpleScriptContext.getAttribute(SimpleScriptContext.java:143)
	at jdk.nashorn.api.scripting.NashornScriptEngine.getScriptName(NashornScriptEngine.java:230)
	at jdk.nashorn.api.scripting.NashornScriptEngine.makeSource(NashornScriptEngine.java:226)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233)
	at com.github.tartaricacid.touhoulittlemaid.danmaku.CustomSpellCardManger.loadCustomSpellCard(CustomSpellCardManger.java:109)
	at com.github.tartaricacid.touhoulittlemaid.danmaku.CustomSpellCardManger.loadInternalSpellCard(CustomSpellCardManger.java:85)
	at com.github.tartaricacid.touhoulittlemaid.danmaku.CustomSpellCardManger.loadInternalSpellCard(CustomSpellCardManger.java:54)
	at com.github.tartaricacid.touhoulittlemaid.danmaku.CustomSpellCardManger.onCustomSpellCardReload(CustomSpellCardManger.java:44)
	at com.github.tartaricacid.touhoulittlemaid.proxy.CommonProxy.init(CommonProxy.java:131)
	at com.github.tartaricacid.touhoulittlemaid.proxy.ClientProxy.init(ClientProxy.java:85)
	at com.github.tartaricacid.touhoulittlemaid.TouhouLittleMaid.init(TouhouLittleMaid.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4617369904 bytes (4403 MB) / 6979321856 bytes (6656 MB) up to 17179869184 bytes (16384 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version      | Source                                        | Signature                                |
	|:----- |:------------------ |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft          | 1.12.2       | minecraft.jar                                 | None                                     |
	| LCHI  | mcp                | 9.42         | minecraft.jar                                 | None                                     |
	| LCHI  | FML                | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge              | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | additional_lights  | 1.12.2-1.2.1 | additional_lights-1.12.2-1.2.1.jar            | None                                     |
	| LCHI  | craftstudioapi     | 1.0.0        | CraftStudio-1.0.0.93-mc1.12-alpha.jar         | None                                     |
	| LCHI  | furenikusroads     | 1.1.10       | Fureniku's+Roads-1.1.10.jar                   | None                                     |
	| LCHI  | cfm                | 5.3.1        | furniture-5.3.1-1.12.2.jar                    | None                                     |
	| LCHI  | nsutils            | 1.6.10       | mcheliext-1.2.1.jar                           | None                                     |
	| LCHI  | mcheliext          | 1.2.1        | mcheliext-1.2.1.jar                           | None                                     |
	| LCHI  | mcmultipart        | 2.5.3        | MCMultiPart-2.5.3.jar                         | None                                     |
	| LCHI  | ngtlib             | 2.4.20       | NGTLib2.4.20-37_forge-1.12.2-14.23.2.2611.jar | None                                     |
	| LCHI  | rtm                | 2.4.23       | RTM2.4.23-42_forge-1.12.2-14.23.2.2611.jar    | None                                     |
	| LCHI  | tektopia           | 1.1.0        | tektopia-1.1.0.jar                            | None                                     |
	| LCHE  | touhou_little_maid | 1.2.5        | touhoulittlemaid-1.12.2-1.2.5-release.jar     | None                                     |
	| LCH   | fix-rtm            | 2.0.23       | fixRtm-2.0.23.jar                             | None                                     |

	Loaded coremods (and transformers): 
PatchingFixRtmCorePlugin (fixRtm-2.0.23.jar)
  com.anatawa12.fixRtm.asm.patching.PatchApplier
FixRtmCorePlugin (fixRtm-2.0.23.jar)
  
JarInJarLoaderCoreMod (fixRtm-2.0.23.jar)
  com.anatawa12.fixRtm.jarInJar.JarInJarPatcher
HookingFixRtmCorePlugin (fixRtm-2.0.23.jar)
  com.anatawa12.fixRtm.asm.hooking.HookingTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 526.47' Renderer: 'NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2'
	RTM Model Status: Initialized 0 models, Using 0 models
	I = Initialized, C = Constructed, SMP = SMP includeds


	| model pack | all | I | C | SMP |
	|:---------- |:--- |:- |:- |:--- |

	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 64
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 526.47
	OpenGlRenderer: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16
```

**Comment by TartaricAcid** [comment]
This issue is currently unresolved

**Comment by TartaricAcid** [comment]
1.12.2 has stopped supporting
