### ISSUE TITLE
[Bug] Failed to load correctly

### ISSUE THREAD

**Issue by miraclematters** [TartaricAcid/TouhouLittleMaid#408]
### Minecraft Version

- [ ] 1.12.2
- [ ] 1.16.5

### What happened?

1. Start game
Is this a conflict with one of my mods? i just really wanted to play with the little maids.

(note: i'm using the 1.18.2 version that was on the curseforge page.)

### Relevant log output

```shell
[18Feb2023 01:10:17.807] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: touhou_little_maid, class com.github.tartaricacid.touhoulittlemaid.TouhouLittleMaid
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.3.jar%23535!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.3.jar%23534!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoSuchFieldError: ENTITIES
	at com.github.tartaricacid.touhoulittlemaid.init.InitEntities.<clinit>(InitEntities.java:42) ~[touhoulittlemaid-1.18.2-1.0.0-alpha.jar%23516!/:?]
	at com.github.tartaricacid.touhoulittlemaid.TouhouLittleMaid.<init>(TouhouLittleMaid.java:27) ~[touhoulittlemaid-1.18.2-1.0.0-alpha.jar%23516!/:?]
	... 14 more
```

**Comment by miraclematters** [comment]
WAIT I WAS CONFUSING 1.18 FOR 1.19 SORRY SORRY that's probably why it wasn't working :(
