### ISSUE TITLE
[Bug] 在龙之冒险3.5.4服务器里生成女仆会报错，但是单机游戏可以正常生成

### ISSUE THREAD

**Issue by Passen** [TartaricAcid/TouhouLittleMaid#452]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [X] 1.16.5
- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20/1.20.1

### What happened?

1.在单机游戏中用女仆刷怪蛋或者其他方式可以生成女仆
2.在3.5.4的龙之冒险服务器里生成女仆时不会生成，右键刷怪蛋也不会生成，后台报错如下

### Relevant log output

```shell
[17:34:32] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388) ~[?:?] {}
        at com.github.tartaricacid.touhoulittlemaid.entity.passive.EntityMaid.func_213386_a(EntityMaid.java:1034) ~[touhou_little_maid:1.1.5] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.entity.EntityType.func_220349_b(EntityType.java:346) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:opotato.mixins.json:api.EntityTypeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.EntityType.func_220342_a(EntityType.java:318) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:opotato.mixins.json:api.EntityTypeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.EntityType.func_220331_a(EntityType.java:313) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:opotato.mixins.json:api.EntityTypeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.item.SpawnEggItem.func_195939_a(SpawnEggItem.java:83) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:SpawnEggItemMixin,pl:mixin:APP:goblintraders.mixins.json:SpawnEggItemMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:637) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:bountifulbaubles-forge.mixins.json:MixinForgeHooks,pl:mixin:APP:lootjs.mixins.json:ForgeHooksMixin,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinForgeHooks,pl:mixin:A}
        at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:186) ~[?:?] {re:mixin,xf:fml:placebo:placeboitemusehook,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,pl:runtimedistcleaner:A,re:classloading,xf:fml:placebo:placeboitemusehook,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,pl:mixin:APP:armorcurve.mixins.json:ArmorDegradationMixin,pl:mixin:APP:tetra.mixins.json:MixinItemStack,pl:mixin:APP:uniquebase.mixins.json:common.item.StackMixin,pl:mixin:APP:kubejs-common.mixins.json:ItemStackMixin,pl:mixin:APP:itemfilters-common.mixins.json:ItemStackMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:350) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:uniquebase.mixins.json:common.InteractionManagerMixin,pl:mixin:APP:bountifulbaubles.mixins.json:MixinServerPlayerInteractionManager,pl:mixin:APP:kubejs-common.mixins.json:PlayerInteractionManagerMixin,pl:mixin:APP:questsadditions.mixins.json:MixinPlayerInteractionManager,pl:mixin:A}
        at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:wings:ServerPlayNetHandlerTransformer,re:classloading,pl:accesstransformer:B,xf:fml:wings:ServerPlayNetHandlerTransformer,pl:mixin:A}
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:mixin,re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:834) [?:?] {}
```

### Contact Details

913526265@qq.com

**Comment by Passen** [comment]
另外，服务器虽然不生成女仆 但是也不会崩溃

**Comment by TartaricAcid** [comment]
你的服务端怎么莫名奇妙不加载女仆的服务端模型数据？女仆的服务端模型数据全部丢失了，变成了 0，你看看你的服务端有问题，你是什么服务端？

**Comment by Passen** [comment]
我是Forge服务端啊，请问这些服务端模型数据按理说应该在哪些文件夹呢？我检查了一下下载的服务端整合包，这就是他们当时发的服务端整合包。应该是本来的服务端就有这个问题的。

> 你的服务端怎么莫名奇妙不加载女仆的服务端模型数据？女仆的服务端模型数据全部丢失了，变成了 0，你看看你的服务端有问题，你是什么服务端？

**Comment by TartaricAcid** [comment]
问题很难断定，我从错误报告中看不出任何东西，无法解答

**Comment by TartaricAcid** [comment]
我猜测可能是你用的服务端的问题，女仆模组会在游戏文件夹下生成一个 tlm-custom-pack 文件夹，并把默认模型放进去加载

我猜测服务端设置了什么权限，不允许程序在此位置写入文件，导致无法加载服务端数据，我想办法解决，但是只能是治标不治本
