### ISSUE TITLE
[Bug] 有自定义模型包时，服务器启动失败

### ISSUE THREAD

**Issue by AlisaAkiron** [TartaricAcid/TouhouLittleMaid#496]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5
- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20/1.20.1

### What happened?

1. 客户端下载了所有的自定义模型包，将 `tlm_custom_pack` 复制到服务器
2. 服务器启动失败

Minecraft 版本：1.20.1
Forge 版本：47.2.0

如果移除服务器上的 `tlm_custom_pack` 后启动服务器，可以启动成功，然后将所有模型复制到服务器的 `tlm_custom_pack` 目录，执行 `/tlm pack reload`，模型可以被正确加载，没有下载自定义模型的客户端在游戏内也能看到服务器上的模型。

### Relevant log output

```shell
[Server] java.lang.NoClassDefFoundError: org/apache/commons/codec/digest/DigestUtils
[Server]        at com.github.tartaricacid.touhoulittlemaid.client.resource.pojo.CustomModelPack.lambda$decorate$0(CustomModelPack.java:127) ~[touhoulittlemaid-1.20.1-release-1.1.8.jar%23308}
[Server]        at java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?] {re:mixin}
[Server]        at com.github.tartaricacid.touhoulittlemaid.client.resource.pojo.CustomModelPack.decorate(CustomModelPack.java:126) ~[touhoulittlemaid-1.20.1-release-1.1.8.jar%23308!/:1.1.8]}
[Server]        at com.github.tartaricacid.touhoulittlemaid.entity.info.ServerCustomPackLoader.loadMaidModelPack(ServerCustomPackLoader.java:178) ~[touhoulittlemaid-1.20.1-release-1.1.8.jar%}
[Server]        at com.github.tartaricacid.touhoulittlemaid.entity.info.ServerCustomPackLoader.readModelFromZipFile(ServerCustomPackLoader.java:125) ~[touhoulittlemaid-1.20.1-release-1.1.8.j}
[Server]        at com.github.tartaricacid.touhoulittlemaid.entity.info.ServerCustomPackLoader.loadPacks(ServerCustomPackLoader.java:89) ~[touhoulittlemaid-1.20.1-release-1.1.8.jar%23308!/:1}
[Server]        at com.github.tartaricacid.touhoulittlemaid.entity.info.ServerCustomPackLoader.initPacks(ServerCustomPackLoader.java:71) ~[touhoulittlemaid-1.20.1-release-1.1.8.jar%23308!/:1}
[Server]        at com.github.tartaricacid.touhoulittlemaid.entity.info.ServerCustomPackLoader.reloadPacks(ServerCustomPackLoader.java:57) ~[touhoulittlemaid-1.20.1-release-1.1.8.jar%23308!/}
[Server]        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
[Server]        at net.minecraftforge.fml.DeferredWorkQueue.lambda$makeRunnable$2(DeferredWorkQueue.java:81) ~[fmlcore-1.20.1-47.2.0.jar%23318!/:?] {}
[Server]        at net.minecraftforge.fml.DeferredWorkQueue.makeRunnable(DeferredWorkQueue.java:76) ~[fmlcore-1.20.1-47.2.0.jar%23318!/:?] {}
[Server]        at net.minecraftforge.fml.DeferredWorkQueue.lambda$runTasks$0(DeferredWorkQueue.java:60) ~[fmlcore-1.20.1-47.2.0.jar%23318!/:?] {}
[Server]        at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?] {}
[Server]        at net.minecraftforge.fml.DeferredWorkQueue.runTasks(DeferredWorkQueue.java:60) ~[fmlcore-1.20.1-47.2.0.jar%23318!/:?] {}
[Server]        at net.minecraftforge.fml.core.ParallelTransition.lambda$finalActivityGenerator$2(ParallelTransition.java:35) ~[forge-1.20.1-47.2.0-universal.jar%23322!/:?] {re:classloading}
[Server]        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
[Server]        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
[Server]        at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:43) ~[fmlcore-1.20.1-47.2.0.jar%23318!/:?] {}
[Server]        at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:28) ~[fmlcore-1.20.1-47.2.0.jar%23318!/:?] {}
[Server]        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:224) ~[fmlcore-1.20.1-47.2.0.jar%23318!/:?] {}
[Server]        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:210) ~[fmlcore-1.20.1-47.2.0.jar%23318!/:?] {}
[Server]        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
[Server]        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:210) ~[fmlcore-1.20.1-47.2.0.jar%23318!/:?] {}
[Server]        at net.minecraftforge.fml.ModLoader.lambda$loadMods$15(ModLoader.java:190) ~[fmlcore-1.20.1-47.2.0.jar%23318!/:?] {}
[Server]        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
[Server]        at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:190) ~[fmlcore-1.20.1-47.2.0.jar%23318!/:?] {}
[Server]        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:31) ~[forge-1.20.1-47.2.0-universal.jar%23322!/:?] {re:classloading}
[Server]        at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23317!/:?] {re:mixin,re:classloading,pl:mixin:A}
[Server]        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
[Server]        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
[Server]        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.0.jar%2369!/:?] {}
[Server]        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.0.jar%2369!/:?] {}
[Server]        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.0.jar%2369!/:?] {}
[Server]        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[Server]        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[Server]        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[Server]        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[Server]        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[Server]        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[Server]        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
[Server]        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
[Server] Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.digest.DigestUtils
[Server]        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
[Server]        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
[Server]        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
[Server]        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
[Server]        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
[Server]        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
[Server]        ... 41 more
```

**Comment by TartaricAcid** [comment]
你的服务端缺 `org/apache/commons/codec/digest/DigestUtils` 包，太怪了，你用的什么服务端

**Comment by AlisaAkiron** [comment]
Minecraft Forge 47.2.0，直接用 Forge 安装器 Install Server 的

**Comment by TartaricAcid** [comment]
我明白了，我的锅，马上就能修好

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/TouhouLittleMaid/commit/2886723dcb9aa84b16280a49aaef98c235d6c9e6

已修复
