### ISSUE TITLE
[Bug] warning from c2me with touhou little maid

### ISSUE THREAD

**Issue by coco875** [TartaricAcid/TouhouLittleMaid#579]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20/1.20.1
- [X] 1.21/1.21.1

### What happened?

1. generate world
2. see logs
3.
(I use c2me with connector)

### Relevant log output

```shell
[26sept.2024 17:24:20.327] [c2me-worker-0/ERROR] [CheckedThreadLocalRandom/]: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: c2me-worker-0)
This is usually NOT a bug in C2ME, but a bug in another mod or in vanilla code. 
Possible solutions: 
  - Find possible causes in the stack trace below and 
    - if caused by another mod, report this to the corresponding mod authors 
    - if no other mods are involved, report this to C2ME 

java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: c2me-worker-0)
	at TRANSFORMER/c2me_fixes_worldgen_threading_issues@0.3.0alpha.0.1501.21.1/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:55) ~[c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-fixes-worldgen-threading-issues-mc1.21.1-0.3.0+alpha.0.150_mapped_moj_1.21.1.jar%231866!/:?]
	at TRANSFORMER/c2me_fixes_worldgen_threading_issues@0.3.0alpha.0.1501.21.1/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38) ~[c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-fixes-worldgen-threading-issues-mc1.21.1-0.3.0+alpha.0.150_mapped_moj_1.21.1.jar%231866!/:?]
	at TRANSFORMER/c2me_fixes_worldgen_threading_issues@0.3.0alpha.0.1501.21.1/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.next(CheckedThreadLocalRandom.java:86) ~[c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-fixes-worldgen-threading-issues-mc1.21.1-0.3.0+alpha.0.150_mapped_moj_1.21.1.jar%231866!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.BitRandomSource.nextDouble(BitRandomSource.java:61) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.md57032d$touhou_little_maid$lambda$createEntityIgnoreException$0$0(com/github/tartaricacid/touhoulittlemaid/mixin/MixinStructureTemplate.java [touhou_little_maid.mixins.json]:25) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at java.base/java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.handler$dhk000$touhou_little_maid$createEntityIgnoreException(com/github/tartaricacid/touhoulittlemaid/mixin/MixinStructureTemplate.java [touhou_little_maid.mixins.json]:23) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.createEntityIgnoreException(net/minecraft/world/level/levelgen/structure/templatesystem/StructureTemplate.java:490) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.addEntitiesToWorld(net/minecraft/world/level/levelgen/structure/templatesystem/StructureTemplate.java:474) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.placeInWorld(net/minecraft/world/level/levelgen/structure/templatesystem/StructureTemplate.java:362) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.place(net/minecraft/world/level/levelgen/structure/pools/SinglePoolElement.java:143) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.place(net/minecraft/world/level/levelgen/structure/PoolElementStructurePiece.java:98) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.postProcess(net/minecraft/world/level/levelgen/structure/PoolElementStructurePiece.java:94) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.levelgen.structure.StructureStart.placeInChunk(net/minecraft/world/level/levelgen/structure/StructureStart.java:92) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.ChunkGenerator.lambda$applyBiomeDecoration$8(net/minecraft/world/level/chunk/ChunkGenerator.java:357) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-32.1.2-jre.jar%23108!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.ChunkGenerator.applyBiomeDecoration(net/minecraft/world/level/chunk/ChunkGenerator.java:356) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.status.ChunkStatusTasks.generateFeatures(net/minecraft/world/level/chunk/status/ChunkStatusTasks.java:154) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.status.ChunkStep.mixinextras$bridge$doWork$14(ChunkStep.java) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.status.ChunkStep.wrapOperation$doa000$c2me_opts_chunk_access$runGenerationTask(com/ishland/c2me/opts/chunk_access/mixin/region_capture/MixinChunkGenerationStep.java [c2me-opts-chunk-access.mixins.json]:26) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.status.ChunkStep.apply(net/minecraft/world/level/chunk/status/ChunkStep.java:33) ~[client-1.21.1-20240808.144430-srg.jar%23527!/:?]
	at TRANSFORMER/c2me_rewrites_chunk_system@0.3.0alpha.0.1501.21.1/com.ishland.c2me.rewrites.chunksystem.common.statuses.VanillaWorldGenerationDelegate.lambda$upgradeToThis$8(VanillaWorldGenerationDelegate.java:123) ~[c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-rewrites-chunk-system-mc1.21.1-0.3.0+alpha.0.150_mapped_moj_1.21.1.jar%231877!/:?]
	at TRANSFORMER/c2me_base@0.3.0alpha.0.1501.21.1/com.ishland.c2me.base.common.scheduler.ScheduledTask.run(ScheduledTask.java:22) [c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-base-mc1.21.1-0.3.0+alpha.0.150-all_mapped_moj_1.21.1.jar%231862!/:?]
	at TRANSFORMER/c2me_base@0.3.0alpha.0.1501.21.1/com.ishland.flowsched.executor.WorkerThread.pollTasks(WorkerThread.java:57) [c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-base-mc1.21.1-0.3.0+alpha.0.150-all_mapped_moj_1.21.1.jar%231862!/:?]
	at TRANSFORMER/c2me_base@0.3.0alpha.0.1501.21.1/com.ishland.flowsched.executor.WorkerThread.run(WorkerThread.java:35) [c2me-fabric-mc1.21.1-0.3.0+alpha.0.150$c2me-base-mc1.21.1-0.3.0+alpha.0.150-all_mapped_moj_1.21.1.jar%231862!/:?]
```

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/TouhouLittleMaid/releases/tag/snapshot-2024122509041735117471

Fixed
