### ISSUE TITLE
[Bug] 删除 TACZ 默认枪械包，导致图标丢失崩溃问题

### ISSUE THREAD

**Issue by Ryen1024** [TartaricAcid/TouhouLittleMaid#590]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20/1.20.1
- [ ] 1.21/1.21.1

### What happened?

当整合包出于某些原因安装了tacz并删除默认枪包时，打开女仆选择工作的界面会因找不到tacz的武器（日志显示为格洛克）而直接崩溃，希望加个图标做备用避免这种情况

### Relevant log output

```shell
Time: 2024-10-13 21:20:11
Description: Rendering screen

java.lang.IllegalArgumentException: Could not found gun id: tacz:glock_17
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar%2388!/:?] {re:mixin}
	at com.tacz.guns.api.item.builder.GunItemBuilder.build(GunItemBuilder.java:69) ~[tacz-1.20.1-1.0.3-all.jar%23478!/:1.0.3] {re:classloading}
	at com.github.tartaricacid.touhoulittlemaid.compat.tacz.task.TaskGunAttack.getIcon(TaskGunAttack.java:41) ~[touhoulittlemaid-1.20.1-release-1.1.12-hotfix2.jar%23486!/:1.1.12-hotfix2] {re:classloading}
	at com.github.tartaricacid.touhoulittlemaid.client.gui.widget.button.TaskButton.m_87963_(TaskButton.java:83) ~[touhoulittlemaid-1.20.1-release-1.1.12-hotfix2.jar%23486!/:1.1.12-hotfix2] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.components.AbstractWidget.m_88315_(AbstractWidget.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23498!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dragonlib.mixins.json:AbstractWidgetAccessor from mod dragonlib,pl:mixin:APP:fancymenu.mixins.json:client.IMixinAbstractWidget from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinAbstractWidget from mod fancymenu,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_88315_(Screen.java:119) ~[client-1.20.1-20230612.114412-srg.jar%23498!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-forge.json:MixinScreen from mod modernui,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenMixin from mod fabric_screen_api_v1,pl:mixin:APP:balm.mixins.json:ScreenAccessor from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenAccessor from mod fabric_screen_api_v1,pl:mixin:APP:controlling.mixins.json:AccessScreen from mod controlling,pl:mixin:APP:konkrete.mixin.json:IMixinScreen from mod konkrete,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen from mod patchouli,pl:mixin:APP:kubejs-common.mixins.json:ScreenMixin from mod kubejs,pl:mixin:APP:dragonlib.mixins.json:ScreenMixin from mod dragonlib,pl:mixin:APP:quark.mixins.json:client.ScreenMixin from mod quark,pl:mixin:APP:fancymenu.mixins.json:client.IMixinScreen from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinScreen from mod fancymenu,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_88315_(AbstractContainerScreen.java:95) ~[client-1.20.1-20230612.114412-srg.jar%23498!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:recipeessentials.mixins.json:RecipeBookButtonMixin from mod recipeessentials,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor from mod balm,pl:mixin:APP:puzzlesapi.common.mixins.json:iteminteractions.client.AbstractContainerScreenMixin from mod puzzlesapi,pl:mixin:APP:puzzlesapi.common.mixins.json:iteminteractions.client.accessor.AbstractContainerScreenAccessor from mod puzzlesapi,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor from mod mousetweaks,pl:mixin:APP:quark.mixins.json:client.ContainerScreenMixin from mod quark,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at com.github.tartaricacid.touhoulittlemaid.client.gui.entity.maid.AbstractMaidContainerGui.m_88315_(AbstractMaidContainerGui.java:116) ~[touhoulittlemaid-1.20.1-release-1.1.12-hotfix2.jar%23486!/:1.1.12-hotfix2] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23498!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-forge.json:MixinScreen from mod modernui,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenMixin from mod fabric_screen_api_v1,pl:mixin:APP:balm.mixins.json:ScreenAccessor from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenAccessor from mod fabric_screen_api_v1,pl:mixin:APP:controlling.mixins.json:AccessScreen from mod controlling,pl:mixin:APP:konkrete.mixin.json:IMixinScreen from mod konkrete,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen from mod patchouli,pl:mixin:APP:kubejs-common.mixins.json:ScreenMixin from mod kubejs,pl:mixin:APP:dragonlib.mixins.json:ScreenMixin from mod dragonlib,pl:mixin:APP:quark.mixins.json:client.ScreenMixin from mod quark,pl:mixin:APP:fancymenu.mixins.json:client.IMixinScreen from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinScreen from mod fancymenu,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.3.7-universal.jar%23503!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.3.7-universal.jar%23503!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.mixinextras$bridge$drawScreen$260(GameRenderer.java) ~[client-1.20.1-20230612.114412-srg.jar%23498!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-forge.json:MixinGameRenderer from mod modernui,pl:mixin:APP:mixins.modernui-textmc.json:MixinGameRenderer from mod modernui,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin from mod moonlight,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_item_rendering.GameRendererMixin from mod modernfix,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing from mod oculus,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin from mod zeta,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod immediatelyfast,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinGameRenderer from mod (unknown),pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin from mod immersive_aircraft,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer from mod railways,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer from mod entity_model_features,pl:mixin:APP:tacz.mixins.json:client.GameRendererMixin from mod tacz,pl:mixin:APP:mixins.artifacts.common.json:item.wearable.nightvisiongoggles.client.GameRendererMixin from mod artifacts,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin from mod alexscaves,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin from mod supplementaries,pl:mixin:APP:fancymenu.forge.mixins.json:client.MixinForgeGameRenderer from mod fancymenu,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor from mod create,pl:mixin:APP:create.mixins.json:client.GameRendererMixin from mod create,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat from mod oculus,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.wrapOperation$gce000$fancymenu$wrapRenderScreenFancyMenu(GameRenderer.java:10117) ~[client-1.20.1-20230612.114412-srg.jar%23498!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-forge.json:MixinGameRenderer from mod modernui,pl:mixin:APP:mixins.modernui-textmc.json:MixinGameRenderer from mod modernui,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin from mod moonlight,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_item_rendering.GameRendererMixin from mod modernfix,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing from mod oculus,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin from mod zeta,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod immediatelyfast,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinGameRenderer from mod (unknown),pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin from mod immersive_aircraft,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer from mod railways,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer from mod entity_model_features,pl:mixin:APP:tacz.mixins.json:client.GameRendererMixin from mod tacz,pl:mixin:APP:mixins.artifacts.common.json:item.wearable.nightvisiongoggles.client.GameRendererMixin from mod artifacts,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin from mod alexscaves,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin from mod supplementaries,pl:mixin:APP:fancymenu.forge.mixins.json:client.MixinForgeGameRenderer from mod fancymenu,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor from mod create,pl:mixin:APP:create.mixins.json:client.GameRendererMixin from mod create,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat from mod oculus,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23498!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.modernui-forge.json:MixinGameRenderer from mod modernui,pl:mixin:APP:mixins.modernui-textmc.json:MixinGameRenderer from mod modernui,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin from mod moonlight,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_item_rendering.GameRendererMixin from mod modernfix,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing from mod oculus,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin from mod zeta,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod immediatelyfast,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinGameRenderer from mod (unknown),pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin from mod immersive_aircraft,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinGameRenderer from mod railways,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer from mod entity_model_features,pl:mixin:APP:tacz.mixins.json:client.GameRendererMixin from mod tacz,pl:mixin:APP:mixins.artifacts.common.json:item.wearable.nightvisiongoggles.client.GameRendererMixin from mod artifacts,pl:mixin:APP:alexscaves.mixins.json:client.GameRendererMixin from mod alexscaves,pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin from mod supplementaries,pl:mixin:APP:fancymenu.forge.mixins.json:client.MixinForgeGameRenderer from mod fancymenu,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor from mod create,pl:mixin:APP:create.mixins.json:client.GameRendererMixin from mod create,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat from mod oculus,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23498!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin from mod alexscaves,pl:mixin:APP:mixins.modernui-forge.json:MixinMinecraft from mod modernui,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:MinecraftClientMixin from mod fabric_screen_api_v1,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement from mod oculus,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor from mod flywheel,pl:mixin:APP:fabric-registry-sync-v0.client.mixins.json:MinecraftClientMixin from mod fabric_registry_sync_v0,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinMinecraftClient from mod immediatelyfast,pl:mixin:APP:valkyrienskies-common.mixins.json:client.MixinMinecraft from mod (unknown),pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft from mod bookshelf,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft from mod railways,pl:mixin:APP:mixins.sodiumdynamiclights.json:MinecraftClientMixin from mod sodiumdynamiclights,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadStart from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient from mod entity_texture_features,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftMixin from mod connectormod,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:fabric-networking-api-v1.client.mixins.json:accessor.MinecraftClientAccessor from mod fabric_networking_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:MinecraftClientMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:kubejs-common.mixins.json:MinecraftClientMixin from mod kubejs,pl:mixin:APP:vs_clockwork-common.mixins.json:content.gravitron.MinecraftAccessor from mod vs_clockwork,pl:mixin:APP:moonlight-common.mixins.json:MinecraftMixin from mod moonlight,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin from mod quark,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin from mod irons_spellbooks,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft from mod fancymenu,pl:mixin:APP:fabric-events-interaction-v0.client.mixins.json:MinecraftClientMixin from mod fabric_events_interaction_v0,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin from mod create,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:APP:connectormod.mixins.json:boot.MinecraftMixin from mod connectormod,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23498!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin from mod alexscaves,pl:mixin:APP:mixins.modernui-forge.json:MixinMinecraft from mod modernui,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:balm.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:fabric-screen-api-v1.mixins.json:MinecraftClientMixin from mod fabric_screen_api_v1,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement from mod oculus,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor from mod flywheel,pl:mixin:APP:fabric-registry-sync-v0.client.mixins.json:MinecraftClientMixin from mod fabric_registry_sync_v0,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinMinecraftClient from mod immediatelyfast,pl:mixin:APP:valkyrienskies-common.mixins.json:client.MixinMinecraft from mod (unknown),pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft from mod bookshelf,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft from mod railways,pl:mixin:APP:mixins.sodiumdynamiclights.json:MinecraftClientMixin from mod sodiumdynamiclights,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft from mod konkrete,pl:mixin:APP:entity_model_features-common.mixins.json:MixinResourceReloadStart from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.MinecraftClientAccessor from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient from mod entity_texture_features,pl:mixin:APP:connectormod.mixins.json:registries.MinecraftMixin from mod connectormod,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:fabric-networking-api-v1.client.mixins.json:accessor.MinecraftClientAccessor from mod fabric_networking_api_v1,pl:mixin:APP:fabric-lifecycle-events-v1.client.mixins.json:MinecraftClientMixin from mod fabric_lifecycle_events_v1,pl:mixin:APP:kubejs-common.mixins.json:MinecraftClientMixin from mod kubejs,pl:mixin:APP:vs_clockwork-common.mixins.json:content.gravitron.MinecraftAccessor from mod vs_clockwork,pl:mixin:APP:moonlight-common.mixins.json:MinecraftMixin from mod moonlight,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin from mod quark,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin from mod irons_spellbooks,pl:mixin:APP:fancymenu.mixins.json:client.IMixinMinecraft from mod fancymenu,pl:mixin:APP:fancymenu.mixins.json:client.MixinMinecraft from mod fancymenu,pl:mixin:APP:fabric-events-interaction-v0.client.mixins.json:MinecraftClientMixin from mod fabric_events_interaction_v0,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin from mod create,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:APP:connectormod.mixins.json:boot.MinecraftMixin from mod connectormod,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin from mod flywheel,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.7.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
```

**Comment by TartaricAcid** [comment]
确实，这是个问题，但是一般情况下为什么要删除默认枪械包啊？

**Comment by Ryen1024** [comment]
大概是因为想限制枪械种类或缩减jei物品列表直接干掉文件吧？摊手

**Comment by Eternal-Snowstorm** [comment]
> 确实，这是个问题，但是一般情况下为什么要删除默认枪械包啊？

部分整合包可能会为了限制枪械的使用而修改枪械配方与可获取范围（比如我的），或者单纯原版枪械不符合画风而会删除原版枪械。希望可以推出备用图标或图标修改路径以应对相关情况QWQ

**Comment by TartaricAcid** [comment]
![image](https://github.com/user-attachments/assets/3a7a0a06-a490-4041-b1bc-66b1837c1094)
解决了，现在把格洛克删掉，图标会被替换成这个
