### ISSUE TITLE
[Bug] java.lang.IllegalArgumentException: Failed to create model for touhou_little_maid:maid

### ISSUE THREAD

**Issue by 1963915695** [TartaricAcid/TouhouLittleMaid#620]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20/1.20.1
- [ ] 1.21/1.21.1

### What happened?

1.start game loding.

### Relevant log output

```shell
Time: 2024-12-10 16:12:14
Description: Rendering overlay

java.lang.IllegalArgumentException: Failed to create model for touhou_little_maid:maid
	at net.minecraft.client.renderer.entity.EntityRenderers.m_257087_(EntityRenderers.java:164) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-rendering-v1.mixins.json:EntityRenderersMixin from mod fabric_rendering_v1,pl:mixin:A,pl:connector_pre_launch:A}
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] {re:mixin}
	at net.minecraft.client.renderer.entity.EntityRenderers.m_174049_(EntityRenderers.java:160) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-rendering-v1.mixins.json:EntityRenderersMixin from mod fabric_rendering_v1,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_6213_(EntityRenderDispatcher.java:360) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mobplayeranimator.mixins.json:client.EntityRendererDispatcherMixin from mod mobplayeranimator,pl:mixin:APP:playerAnimator-common.mixins.json:firstPerson.EntityRenderDispatcherMixin from mod playeranimator,pl:mixin:APP:tslatentitystatus.mixins.json:client.EntityRenderDispatcherMixin from mod tslatentitystatus,pl:mixin:APP:sodium-extra.mixins.json:profiler.MixinEntityRenderDispatcher from mod embeddium_extra,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.shipyard_entities.MixinEntityRenderDispatcher from mod valkyrienskies,pl:mixin:APP:mixins.oculus.json:MixinEntityRenderDispatcher from mod oculus,pl:mixin:APP:mixins.oculus.json:entity_render_context.MixinEntityRenderDispatcher from mod oculus,pl:mixin:APP:mixins.oculus.compat.sodium.json:copyEntity.shadows.EntityRenderDispatcherMixin from mod oculus,pl:mixin:APP:embeddiumplus.mixin.json:entitydistance.EntityDispatcherMixin from mod embeddiumplus,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.EntityRenderDispatcherAccessor from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:rendering.MixinEntityRenderDispatcher from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:entity.misc.MixinEntityRenderDispatcher from mod entity_texture_features,pl:mixin:APP:owo.mixins.json:ui.EntityRenderDispatcherMixin from mod owo,pl:mixin:APP:mixins.bfrc.json:MixinEntityRender from mod brute_force_rendering_culling,pl:mixin:APP:freecam.mixins.json:EntityRenderDispatcherAccessor from mod freecam,pl:mixin:APP:freecam.mixins.json:EntityRenderDispatcherMixin from mod freecam,pl:mixin:APP:mixins.oculus.compat.sodium.json:vertex_format.entity.MixinEntityRenderDispatcher from mod oculus,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.packs.resources.ResourceManagerReloadListener.m_10759_(ResourceManagerReloadListener.java:15) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:classloading,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:SimpleResourceReloadMixin from mod fabric_resource_loader_v0,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:computing_frames,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:connector_pre_launch:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:imblocker:window_focus_asm,xf:fml:customskinloader:MinecraftTransformer,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:imblocker:window_focus_asm,xf:fml:customskinloader:MinecraftTransformer,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:imblocker:window_focus_asm,xf:fml:customskinloader:MinecraftTransformer,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:imblocker:window_focus_asm,xf:fml:customskinloader:MinecraftTransformer,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[endofdays.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin from mod smoothboot,pl:mixin:APP:mixins.emibridge.json:MainEntrypointMixin from mod connectorextras_emi_bridge,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110) ~[?:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:103) ~[?:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.forEach(java.util.function.BiConsumer)" because "com.github.tartaricacid.touhoulittlemaid.entity.backpack.BackpackManager.BACKPACK_ID_MAP" is null
	at com.github.tartaricacid.touhoulittlemaid.entity.backpack.BackpackManager.initClient(BackpackManager.java:57) ~[%5B车万女仆%5D%20touhoulittlemaid-1.20.1-release-1.1.13.jar%23409!/:1.1.13] {re:classloading}
	at com.github.tartaricacid.touhoulittlemaid.client.renderer.entity.layer.LayerMaidBackpack.<init>(LayerMaidBackpack.java:22) ~[%5B车万女仆%5D%20touhoulittlemaid-1.20.1-release-1.1.13.jar%23409!/:1.1.13] {re:classloading}
	at com.github.tartaricacid.touhoulittlemaid.client.renderer.entity.EntityMaidRenderer.<init>(EntityMaidRenderer.java:43) ~[%5B车万女仆%5D%20touhoulittlemaid-1.20.1-release-1.1.13.jar%23409!/:1.1.13] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRenderers.redirect$bbc000$fabric_rendering_v1$createEntityRenderer(EntityRenderers.java:543) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-rendering-v1.mixins.json:EntityRenderersMixin from mod fabric_rendering_v1,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.client.renderer.entity.EntityRenderers.m_257087_(EntityRenderers.java:162) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-rendering-v1.mixins.json:EntityRenderersMixin from mod fabric_rendering_v1,pl:mixin:A,pl:connector_pre_launch:A}
	... 35 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	Touhou Little Maid (touhou_little_maid), Version: 1.1.13
		at TRANSFORMER/touhou_little_maid@1.1.13/com.github.tartaricacid.touhoulittlemaid.entity.backpack.BackpackManager.initClient(BackpackManager.java:57)

	Fabric Rendering (v1) (fabric_rendering_v1), Version: 3.0.8+66e9a48f77
		Mixin class: net.fabricmc.fabric.mixin.client.rendering.EntityRenderersMixin
		Target: net.minecraft.client.renderer.entity.EntityRenderers
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.entity.EntityRenderers.redirect$bbc000$fabric_rendering_v1$createEntityRenderer(EntityRenderers.java:543)
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRenderers.m_257087_(EntityRenderers.java:164) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-rendering-v1.mixins.json:EntityRenderersMixin from mod fabric_rendering_v1,pl:mixin:A,pl:connector_pre_launch:A}
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] {re:mixin}
	at net.minecraft.client.renderer.entity.EntityRenderers.m_174049_(EntityRenderers.java:160) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-rendering-v1.mixins.json:EntityRenderersMixin from mod fabric_rendering_v1,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_6213_(EntityRenderDispatcher.java:360) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mobplayeranimator.mixins.json:client.EntityRendererDispatcherMixin from mod mobplayeranimator,pl:mixin:APP:playerAnimator-common.mixins.json:firstPerson.EntityRenderDispatcherMixin from mod playeranimator,pl:mixin:APP:tslatentitystatus.mixins.json:client.EntityRenderDispatcherMixin from mod tslatentitystatus,pl:mixin:APP:sodium-extra.mixins.json:profiler.MixinEntityRenderDispatcher from mod embeddium_extra,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.shipyard_entities.MixinEntityRenderDispatcher from mod valkyrienskies,pl:mixin:APP:mixins.oculus.json:MixinEntityRenderDispatcher from mod oculus,pl:mixin:APP:mixins.oculus.json:entity_render_context.MixinEntityRenderDispatcher from mod oculus,pl:mixin:APP:mixins.oculus.compat.sodium.json:copyEntity.shadows.EntityRenderDispatcherMixin from mod oculus,pl:mixin:APP:embeddiumplus.mixin.json:entitydistance.EntityDispatcherMixin from mod embeddiumplus,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.EntityRenderDispatcherAccessor from mod entity_model_features,pl:mixin:APP:entity_model_features-common.mixins.json:rendering.MixinEntityRenderDispatcher from mod entity_model_features,pl:mixin:APP:entity_texture_features-common.mixins.json:entity.misc.MixinEntityRenderDispatcher from mod entity_texture_features,pl:mixin:APP:owo.mixins.json:ui.EntityRenderDispatcherMixin from mod owo,pl:mixin:APP:mixins.bfrc.json:MixinEntityRender from mod brute_force_rendering_culling,pl:mixin:APP:freecam.mixins.json:EntityRenderDispatcherAccessor from mod freecam,pl:mixin:APP:freecam.mixins.json:EntityRenderDispatcherMixin from mod freecam,pl:mixin:APP:mixins.oculus.compat.sodium.json:vertex_format.entity.MixinEntityRenderDispatcher from mod oculus,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.packs.resources.ResourceManagerReloadListener.m_10759_(ResourceManagerReloadListener.java:15) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:classloading,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:fabric-resource-loader-v0.mixins.json:SimpleResourceReloadMixin from mod fabric_resource_loader_v0,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:computing_frames,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:computing_frames,pl:accesstransformer:B,pl:connector_pre_launch:A,re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:connector_pre_launch:A}
-- Overlay render details --
Details:
	Overlay name: net.minecraftforge.client.loading.ForgeLoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:957) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:methane.mixins.json:GameRendererMixin from mod methane,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin from mod moonlight,pl:mixin:APP:prefabricated.mixins.json:ClientWorldMixin from mod prefabricated,pl:mixin:APP:tslatentitystatus.mixins.json:client.GameRendererMixin from mod tslatentitystatus,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin from mod zeta,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer from mod embeddium_extra,pl:mixin:APP:valkyrienskies-common.mixins.json:client.renderer.MixinGameRenderer from mod valkyrienskies,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer from mod oculus,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing from mod oculus,pl:mixin:APP:embeddiumplus.mixin.json:darkness.GameRendererMixin from mod embeddiumplus,pl:mixin:APP:entity_model_features-common.mixins.json:MixinGameRenderer from mod entity_model_features,pl:mixin:APP:scguns.mixins.json:client.GameRendererMixin from mod (unknown),pl:mixin:APP:mixins.cosmos.json:MixinGameRenderer from mod cosmos,pl:mixin:APP:owo.mixins.json:shader.GameRendererMixin from mod owo,pl:mixin:APP:forge-mca.mixin.json:client.MixinGameRenderer from mod (unknown),pl:mixin:APP:tacz.mixins.json:client.GameRendererMixin from mod tacz,pl:mixin:APP:mixins.artifacts.common.json:item.wearable.nightvisiongoggles.client.GameRendererMixin from mod artifacts,pl:mixin:APP:freecam.mixins.json:GameRendererMixin from mod freecam,pl:mixin:APP:fancymenu.forge.mixins.json:client.MixinForgeGameRenderer from mod fancymenu,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat from mod oculus,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:imblocker:window_focus_asm,xf:fml:customskinloader:MinecraftTransformer,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:imblocker:window_focus_asm,xf:fml:customskinloader:MinecraftTransformer,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23516!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:imblocker:window_focus_asm,xf:fml:customskinloader:MinecraftTransformer,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:imblocker:window_focus_asm,xf:fml:customskinloader:MinecraftTransformer,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[endofdays.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin from mod smoothboot,pl:mixin:APP:mixins.emibridge.json:MainEntrypointMixin from mod connectorextras_emi_bridge,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?] {}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110) ~[?:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:103) ~[?:?] {}
```

### Contact Details

196391595@qq.com

**Comment by TartaricAcid** [comment]
你是使用了信雅互联相关的模组么？

这个错误太奇怪了，FMLCommonSetupEvent 居然比 EntityRenderersEvent.RegisterRenderers 晚执行，导致 BACKPACK_ID_MAP 变量为 null

最好提供完整的错误报告，或者加载的模组，我好判断原因

**Comment by TartaricAcid** [comment]
fixed https://github.com/TartaricAcid/TouhouLittleMaid/commit/5973791102c0e02b9d3b47d832fe231cdd74ff17
