### ISSUE TITLE
[Bug] mohist1.20.1 和BKCommonLib插件冲突

### ISSUE THREAD

**Issue by LCEN1361** [TartaricAcid/TouhouLittleMaid#631]
### Minecraft Version

- [ ] 1.12.2 (End of support)
- [ ] 1.16.5 (End of support)
- [ ] 1.18.2
- [ ] 1.19.2
- [x] 1.20/1.20.1
- [ ] 1.21/1.21.1

### What happened?

1.只要世界中有女仆/用魂符放置一个女仆 服务器就会发送一次报错
2.游戏没有崩溃玩起来也没有异常，但是刷屏的报错好烦
3.BKCommonLib是myworld多世界插件的前置 改它的配置文件也不能解决
4.mohist-917 只有这个前置和女仆模组

### Relevant log output

```shell
它说什么正文太长，我就把会一直刷屏的报错截下来了
[11:20:11 ERROR]: Error handling vehicle mount packets for player DF_LCEN
java.lang.IllegalStateException: Failed to construct entity of type touhou_little_maid:maid
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mpldefgen69011e4b.findClassFromEntityTypes(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mpldefgen69011e4b.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.logic.EntityTypingHandler_1_14$Handler$impl.findClassFromEntityTypes(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.logic.EntityTypingHandler_1_14.getClassFromEntityTypes(EntityTypingHandler_1_14.java:140) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mpldefgen3a3cdcb5.getEntityClassInst(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mpldefgen3a3cdcb5.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1637) ~[?:?]
        at com.bergerkiller.bukkit.common.entity.CommonEntityType.byNMSEntityTypeRaw(CommonEntityType.java:412) ~[?:?]
        at com.bergerkiller.bukkit.common.entity.CommonEntityType.byNMSEntityType(CommonEntityType.java:457) ~[?:?]
        at com.bergerkiller.generated.net.minecraft.network.protocol.game.PacketPlayOutSpawnEntityHandle.getCommonEntityType(PacketPlayOutSpawnEntityHandle.java:84) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.mounting.VehicleMountHandler_BaseImpl.lambda$handlePacketSend$10(VehicleMountHandler_BaseImpl.java:467) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.mounting.VehicleMountHandler_BaseImpl.synchronizeAndQueuePackets(VehicleMountHandler_BaseImpl.java:504) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.mounting.VehicleMountHandler_BaseImpl.handlePacketSend(VehicleMountHandler_BaseImpl.java:394) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.CommonVehicleMountManager$3.onMonitorPacketSend(CommonVehicleMountManager.java:73) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.network.PacketHandlerRegistration.handlePacketSendMonitor(PacketHandlerRegistration.java:231) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.network.PacketHandlerRegistration.handlePacketSend(PacketHandlerRegistration.java:201) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.network.PacketHandlerRegistration.lambda$handlePacketSend$0(PacketHandlerRegistration.java:192) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker$mpldefgen51782fe4.filterSubPackets(Unknown Source) ~[?:?]
        at com.bergerkiller.generated.net.minecraft.network.protocol.game.ClientboundBundlePacketHandle$impl.filterSubPackets(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.network.PacketHandlerRegistration.handlePacketSend(PacketHandlerRegistration.java:192) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.network.PacketHandlerHooked.handlePacketSend(PacketHandlerHooked.java:183) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.network.CommonPacketHandler$CommonChannelListener.write(CommonPacketHandler.java:131) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar%23177!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar%23177!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.82.Final.jar%23177!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.82.Final.jar%23177!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.82.Final.jar%23177!/:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.82.Final.jar%23177!/:4.1.82.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.82.Final.jar%23177!/:4.1.82.Final]
        at net.minecraft.network.Connection.m_243087_(Connection.java:233) ~[server-1.20.1-20230612.114412-srg.jar%23200!/:?]
        at net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:222) ~[server-1.20.1-20230612.114412-srg.jar%23200!/:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar%23174!/:4.1.82.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar%23174!/:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar%23174!/:4.1.82.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.82.Final.jar%23177!/:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar%23174!/:4.1.82.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar%23174!/:4.1.82.Final]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceKey.m_135782_()" because the return value of "net.minecraft.world.level.Level.m_46472_()" is null
        at com.github.tartaricacid.touhoulittlemaid.entity.passive.EntityMaid.<init>(EntityMaid.java:239) ~[touhoulittlemaid-1.20.1-release-1.1.13.jar%23198!/:1.1.13]
        at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:553) ~[server-1.20.1-20230612.114412-srg.jar%23200!/:?]
        ... 38 more
```

**Comment by TartaricAcid** [comment]
还有更完整的文件么，这一小块还是有些不足

**Comment by LCEN1361** [comment]
[latest.log](https://github.com/user-attachments/files/18462431/latest.log)

[debug.log](https://github.com/user-attachments/files/18462432/debug.log)这是服务器下的两个日志文件。mohist，女仆，BKCommonLib都是最新的

**Comment by TartaricAcid** [comment]
查了下是 BKCommonLib 多世界插件的 `net.minecraft.world.level.Level#dimension` 参数居然返回了 null，这个在原版代码下是 NotNull 的

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/TouhouLittleMaid/releases/download/snapshot-2025012106061737439561/touhoulittlemaid-1.20.1-release-1.1.14.jar

试试看

**Comment by TartaricAcid** [comment]
好了么好了么

**Comment by LCEN1361** [comment]
没有报错和刷屏了，感谢
