### ISSUE TITLE
今天在服务器测试了下，放置女仆的时候报错了！

### ISSUE THREAD

**Issue by Coloryr** [TartaricAcid/TouhouLittleMaid#67]
>[01:01:11][Server thread/ERROR]: Encountered an exception while constructing entity 'touhou_little_maid:entity.passive.maid' 
 java.lang.reflect.InvocationTargetException: null
at sun.reflect.GeneratedConstructorAccessor184.newInstance(Unknown Source) ~[?:?]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_222]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_222]
at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:306) [EntityEntryBuilder$ConstructorFactory.class:git-1.12.2-e92cd59]
at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:292) [EntityEntryBuilder$ConstructorFactory.class:git-1.12.2-e92cd59]
at net.minecraftforge.fml.common.registry.EntityEntry.newInstance(EntityEntry.java:67) [EntityEntry.class:git-1.12.2-e92cd59]
at net.minecraft.entity.EntityList.func_188429_b(EntityList.java:206) [vi.class:?]
at net.minecraft.item.ItemMonsterPlacer.spawnCreature(ItemMonsterPlacer.java:234) [ajv.class:?]
at net.minecraft.item.ItemMonsterPlacer.func_77840_a(ItemMonsterPlacer.java:223) [ajv.class:?]
at net.minecraft.item.ItemMonsterPlacer.func_180614_a(ItemMonsterPlacer.java:95) [ajv.class:?]
at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:915) [ForgeHooks.class:git-1.12.2-e92cd59]
at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:213) [aip.class:?]
at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:590) [or.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1144) [pa.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:59) [ma.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:13) [ma.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
at net.minecraft.util.Util.func_181617_a(Util.java:50) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:870) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:806) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:660) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoSuchFieldError: isDebugFloorOpen
at com.github.tartaricacid.touhoulittlemaid.entity.passive.EntityMaid.<init>(EntityMaid.java:110) ~[EntityMaid.class:?]
... 25 more

**Comment by TartaricAcid** [comment]
哇，大哥你先别用自己构建的版本啊（哭脸）

不过还是感谢排错

**Comment by Coloryr** [comment]
手动排雷（确信）

**Comment by TartaricAcid** [comment]
我一般在发布前才会进行一次服务端测试

**Comment by Coloryr** [comment]
我见有更新直接构建了
